version:  '3.3'

services:

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: on-failure
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - './docker/nginx/certs:/etc/nginx/certs:ro'
    ports:
      - "443:443"

  api:
    container_name: api
    build:
      context: ./docker/php
    volumes:
      - '/app:/app'
    restart: on-failure
    environment:
      - 'COMPOSER_RUNTIME_ENV=virtualbox'
      - 'COMPOSER_HOME=/tmp/composer'
      - 'COMPOSER_ALLOW_SUPERUSER=1'
      - 'XDEBUG_MODE=develop,debug'
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
    depends_on:
      - database

  messenger:
    container_name: messenger
    build:
      context: ./docker/php
    volumes:
      - '/app:/app'
    restart: always
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
    depends_on:
      - database
    command: sh -c 'sleep 5 && php bin/console messenger:consume async -vv'

  database:
    container_name: database
    image: mariadb:10.10.3
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agh

volumes:
  db-data:
